AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Exam Study App Backend

Parameters:
  CognitoAutoConfirm:
    Type: String
    Default: 'true'
    AllowedValues: ['true', 'false']
    Description: メール確認をスキップして即時サインアップ可能にする（開発用）

Globals:
  Function:
    Timeout: 10
    Runtime: nodejs20.x
    MemorySize: 256
    Architectures:
      - arm64

Resources:
  # Cognito User Pool
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${AWS::StackName}-UserPool'
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Schema:
        - Name: email
          Required: true
          Mutable: false
        - Name: preferred_username
          Required: false
          Mutable: true
        - Name: picture
          Required: false
          Mutable: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireUppercase: true
          RequireLowercase: true
          RequireNumbers: true
          RequireSymbols: false
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref UserPool
      ClientName: !Sub '${AWS::StackName}-WebClient'
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      SupportedIdentityProviders:
        - COGNITO
      TokenValidityUnits:
        AccessToken: hours
        IdToken: hours
        RefreshToken: days
      AccessTokenValidity: 1
      IdTokenValidity: 1
      RefreshTokenValidity: 30
      PreventUserExistenceErrors: ENABLED

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: !Sub '${AWS::StackName}-${AWS::AccountId}'
      UserPoolId: !Ref UserPool

  # DynamoDB テーブル
  QuestionsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-Questions'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE

  # 回答履歴テーブル
  AnswerHistoryTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-AnswerHistory'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # 問題統計テーブル
  QuestionStatsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${AWS::StackName}-QuestionStats'
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  # Lambda 関数
  GetQuestionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: dist/functions/getQuestions/handler.handler
      Environment:
        Variables:
          QUESTIONS_TABLE_NAME: !Ref QuestionsTable
          QUESTION_STATS_TABLE_NAME: !Ref QuestionStatsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref QuestionsTable
        - DynamoDBReadPolicy:
            TableName: !Ref QuestionStatsTable
      Events:
        GetQuestions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /questions
            Method: GET

  SubmitAnswerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: dist/functions/submitAnswer/handler.handler
      Environment:
        Variables:
          QUESTIONS_TABLE_NAME: !Ref QuestionsTable
          ANSWER_HISTORY_TABLE_NAME: !Ref AnswerHistoryTable
          QUESTION_STATS_TABLE_NAME: !Ref QuestionStatsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref QuestionsTable
        - DynamoDBCrudPolicy:
            TableName: !Ref AnswerHistoryTable
        - DynamoDBCrudPolicy:
            TableName: !Ref QuestionStatsTable
      Events:
        SubmitAnswer:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /answers
            Method: POST
            Auth:
              Authorizer: CognitoAuthorizer

  GetStatsSummaryFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: dist/functions/getStatsSummary/handler.handler
      Environment:
        Variables:
          QUESTIONS_TABLE_NAME: !Ref QuestionsTable
          QUESTION_STATS_TABLE_NAME: !Ref QuestionStatsTable
          ANSWER_HISTORY_TABLE_NAME: !Ref AnswerHistoryTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref QuestionsTable
        - DynamoDBReadPolicy:
            TableName: !Ref QuestionStatsTable
        - DynamoDBReadPolicy:
            TableName: !Ref AnswerHistoryTable
      Events:
        GetStatsSummary:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /stats/summary
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  GetHistoryQuestionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: backend/
      Handler: dist/functions/getHistoryQuestions/handler.handler
      Environment:
        Variables:
          QUESTIONS_TABLE_NAME: !Ref QuestionsTable
          QUESTION_STATS_TABLE_NAME: !Ref QuestionStatsTable
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref QuestionsTable
        - DynamoDBReadPolicy:
            TableName: !Ref QuestionStatsTable
      Events:
        GetHistoryQuestions:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /history/questions
            Method: GET
            Auth:
              Authorizer: CognitoAuthorizer

  # HTTP API
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      Auth:
        Authorizers:
          CognitoAuthorizer:
            IdentitySource: $request.header.Authorization
            JwtConfiguration:
              issuer: !Sub 'https://cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}'
              audience:
                - !Ref UserPoolClient
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET
          - POST
          - OPTIONS
        AllowHeaders:
          - Content-Type
          - Authorization
        MaxAge: 3600

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'

  UserPoolId:
    Description: Cognito User Pool ID
    Value: !Ref UserPool

  UserPoolClientId:
    Description: Cognito User Pool Client ID (for frontend)
    Value: !Ref UserPoolClient

  UserPoolRegion:
    Description: AWS Region for Cognito
    Value: !Ref AWS::Region

  QuestionsTableName:
    Description: DynamoDB Questions table name
    Value: !Ref QuestionsTable

  AnswerHistoryTableName:
    Description: DynamoDB AnswerHistory table name
    Value: !Ref AnswerHistoryTable

  QuestionStatsTableName:
    Description: DynamoDB QuestionStats table name
    Value: !Ref QuestionStatsTable
